name: Github Secret to Env File
description: Github Secret to Env File without base64
author: Igor Suvorov
branding:
  icon: file-plus
  color: orange

inputs:
  content:
    description: Content for the file
    required: true
  filename:
    description: Name of the file for the content (allow directory)
    required: true
  chmod:
    description: Defines the file CHMOD permission of the created file
    required: false 
    default: '644'
  content2:
    description: Content for the file2
    required: false
  filename2:
    description: Name of the file2 for the content (allow directory)
    required: false
  chmod2:
    description: Defines the file2 CHMOD permission of the created file
    required: false 

runs:
  using: node20
  main: main.js
  post: post.js
